# need GROQ_API_KEY

chat_model:
  provider: groq
  model: llama3-70b-8192
  temperature: 0.2
  top_p: 0.5

agent:
  additional_stop_sequences: [ "<|eot_id|>" ] # workaround for llama3
  max_iterations: 10
